### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: absolute srcpath does not exist     at symlinkPathsSync

### ISSUE THREAD

**Issue by astorije** [wclr/yalc#98]
Hi there! I'm getting the following error when running `yalc add`:

```
$ yalc add my-package
(node:71346) UnhandledPromiseRejectionWarning: Error: absolute srcpath does not exist
    at symlinkPathsSync (/Users/astorije/.config/yarn/global/node_modules/fs-extra/lib/ensure/symlink-paths.js:71:24)
    at createSymlinkSync (/Users/astorije/.config/yarn/global/node_modules/fs-extra/lib/ensure/symlink.js:50:20)
    at addBinScript (/Users/astorije/.config/yarn/global/node_modules/yalc/src/add.js:169:41)
    at Object.<anonymous> (/Users/astorije/.config/yarn/global/node_modules/yalc/src/add.js:179:45)
    at step (/Users/astorije/.config/yarn/global/node_modules/yalc/src/add.js:32:23)
    at Object.next (/Users/astorije/.config/yarn/global/node_modules/yalc/src/add.js:13:53)
    at fulfilled (/Users/astorije/.config/yarn/global/node_modules/yalc/src/add.js:4:58)
(node:71346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:71346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This does not happen for all packages. Maybe coincidentally, but the package whose install fails has a `bin` script.

It installs as expected when commenting out those 2 lines: https://github.com/whitecolor/yalc/blob/a70d42b9cfa10fa3063563d98cee33db1dab80c5/src/add.ts#L168-L169

Run with the following versions:

```
$ yalc --version
1.0.0-pre.34
$ yarn --version
1.17.3
```

Installed with `yarn global add yalc`.

Yalc is a godsend, thank you so much!

**Comment by marvinroger** [comment]
I can confirm that this issue appears when there's a `bin` script.

**Comment by astorije** [comment]
@whitecolor, sorry to bother, do you think you could help us with this one? 🙏

**Comment by komanton** [comment]
In my case, there was a conflict between npm link and yalc link commands.
I.e. you should try to unlink all previous 'npm link's

**Comment by alexseitsinger** [comment]
I have this issue, too. Package has a bin script(s)...

**Comment by zanerock** [comment]
I'm getting this error as well. Package has bin scripts and (I'm 95% sure) nothing is 'npm link'ed in either the source or consumer package. (1.0.0-pre35)

**Comment by Eddie-CooRo** [comment]
@zanerock Thanks
I was getting the same error. Turned out I missed the `.js` at the end of the bin script path.

**Comment by gabrieloczkowski** [comment]
Problem still exists. I have correct and existing path but still receiving the error.
```
    "bin": {
        "command": "./dist/cli/command/index.js"
    },
```
Looks like it doesn't copy files when `bin` option is provided.

@whitecolor Any update on that?

**Comment by gabrieloczkowski** [comment]
I resolved my problem and it turns out it was not related to `bin` option.
My problem was that I imported `package.json` into codebase so builded project (`dist` directory) also had it's own `package.json` but it shouldn't.
Additionally I used `files: ['dist']` option and at the end `yalc publish` generated only `package.json` and empty `dist` directory even when builded project had everything. So I assume there can be an issue with `yalc publish` when there are multiple `package.json` cc: @whitecolor .
